CREATE TABLE `communities` (`id` text PRIMARY KEY NOT NULL, `slug` text NOT NULL, `name` text NOT NULL, `description` text DEFAULT '' NOT NULL, `owner_wallet_hash` text NOT NULL, `created_at` integer NOT NULL);
CREATE UNIQUE INDEX `idx_communities_slug` ON `communities` (`slug`);
CREATE TABLE `events` (`id` text PRIMARY KEY NOT NULL, `community_id` text NOT NULL, `title` text NOT NULL, `status` text NOT NULL, `starts_at` integer, `launched_config_json` text, `config_version` integer DEFAULT 1 NOT NULL, `created_at` integer NOT NULL, FOREIGN KEY (`community_id`) REFERENCES `communities`(`id`) ON UPDATE no action ON DELETE no action);
CREATE INDEX `idx_events_community_status` ON `events` (`community_id`,`status`);
CREATE TABLE `rounds` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL, `position` integer NOT NULL, `type` text NOT NULL, `prompt` text NOT NULL, `config_json` text NOT NULL, FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE no action);
CREATE UNIQUE INDEX `idx_rounds_event_position` ON `rounds` (`event_id`,`position`);
CREATE TABLE `participants` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL, `nickname` text NOT NULL, `wallet_hash` text, `device_hash` text, `team_id` text, `session_version` integer DEFAULT 1 NOT NULL, `joined_at` integer NOT NULL, `last_seen_at` integer NOT NULL, FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE no action);
CREATE INDEX `idx_participants_event` ON `participants` (`event_id`);
CREATE UNIQUE INDEX `idx_participants_event_wallet` ON `participants` (`event_id`,`wallet_hash`);
CREATE TABLE `answers` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL, `round_id` text NOT NULL, `participant_id` text NOT NULL, `answer_json` text NOT NULL, `received_at` integer NOT NULL, `accepted` integer NOT NULL, `score` integer DEFAULT 0 NOT NULL, FOREIGN KEY (`event_id`) REFERENCES `events`(`id`), FOREIGN KEY (`round_id`) REFERENCES `rounds`(`id`), FOREIGN KEY (`participant_id`) REFERENCES `participants`(`id`));
CREATE UNIQUE INDEX `idx_answers_round_participant` ON `answers` (`round_id`,`participant_id`);
CREATE INDEX `idx_answers_event_round` ON `answers` (`event_id`,`round_id`);
CREATE TABLE `rewards` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL, `state` text NOT NULL, `amount_luna` text NOT NULL, `funding_tx_hash` text, `rules_json` text NOT NULL, `updated_at` integer NOT NULL, FOREIGN KEY (`event_id`) REFERENCES `events`(`id`));
CREATE UNIQUE INDEX `idx_rewards_event` ON `rewards` (`event_id`);
CREATE TABLE `payouts` (`id` text PRIMARY KEY NOT NULL, `reward_id` text NOT NULL, `participant_id` text NOT NULL, `amount_luna` text NOT NULL, `state` text NOT NULL, `tx_hash` text, `failure_code` text, `updated_at` integer NOT NULL, FOREIGN KEY (`reward_id`) REFERENCES `rewards`(`id`), FOREIGN KEY (`participant_id`) REFERENCES `participants`(`id`));
CREATE UNIQUE INDEX `idx_payouts_reward_participant` ON `payouts` (`reward_id`,`participant_id`);
CREATE TABLE `event_audit` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL, `actor_hash` text NOT NULL, `action` text NOT NULL, `payload_json` text NOT NULL, `created_at` integer NOT NULL, FOREIGN KEY (`event_id`) REFERENCES `events`(`id`));
CREATE INDEX `idx_event_audit_event_created` ON `event_audit` (`event_id`,`created_at`);
PRAGMA optimize;
